[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jaydroid"
version = "0.1.1"
description = "A beginner-friendly Python wrapper for simulating Android actions via ADB (tap, swipe, power on/off)."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "Johnston Kweku Abubakar" }
]
keywords = ["adb", "android", "automation", "adb-wrapper"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/johnston-kweku/jaydroid"
Issues = "https://github.com/johnston-kweku/jaydroid/issues"

[tool.setuptools.packages.find]
where = ["src"]